apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dc-logbook
type: Opaque
stringData:
  # DATABASE CONFIG
  DATABASE_URL: "postgresql://user:password@host:port/dbname"
  
  # SECURITY
  SECRET_KEY: "ganti-dengan-yang-baru-dan-rahasia"
  ALLOW_SETUP_ADMIN: "false"
  
  # CORS
  ALLOWED_ORIGINS: "https://logbook.bkn.go.id,https://dev-logbook.bkn.go.id"
